name: Docker Image Push

on:
  push:
    branches:
      - "main"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set matrix
        id: set-matrix
        run: echo "matrix=$(bash ./bin/generate_matrix.sh ${{ github.event.before }} ${{ github.event.after }} | xargs )" >> $GITHUB_OUTPUT
  docker:
    needs:
      - generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Docker Hub login
        uses: docker/login-action@releases/v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_SUBMITTY }}
          password: ${{ secrets.DOCKER_PASSWORD_SUBMITTY }}

      - name: Build and push docker
        uses: docker/build-push-action@releases/v3
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.tags }}
