name: Git Diff Workflow
on: [push]

jobs:
  git-diff-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify HEAD^ reference
        id: verify-ref
        run: |
          if git rev-parse --quiet --verify HEAD^; then
            echo "::set-output name=ref::HEAD^"
          else
            echo "::set-output name=ref::$(git rev-parse HEAD~1)"
          fi

      - name: Run Git Diff
        run: |
          git diff --name-only ${{ steps.verify-ref.outputs.ref }}
          echo "::set-output name=diff-files::$(git diff --name-only ${{ steps.verify-ref.outputs.ref }})"
