name: Git Diff Workflow
on: [push]

jobs:
  git-diff-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Previous Commit
        id: previous-commit
        run: |
          echo "::set-output name=commit-hash::$(git log --pretty=format:%H | tail -n 1)"

      - name: Run Git Diff
        run: |
          git diff --name-only ${{ steps.previous-commit.outputs.commit-hash }}
          echo "::set-output name=diff-files::$(git diff --name-only ${{ steps.previous-commit.outputs.commit-hash }})"
