name: Git Diff Workflow
on: [push]

jobs:
  git-diff-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Previous Commit
        id: previous-commit
        run: |
          echo "COMMIT_HASH=$(git log --pretty=format:%H | tail -n 1)" >> $GITHUB_ENV

      - name: Run Git Diff
        id: git-diff
        run: |
          git diff --name-only $COMMIT_HASH
          echo "DIFF_FILES=$(git diff --name-only $COMMIT_HASH)" >> $GITHUB_ENV

      - name: Use Git Diff Output
        run: |
          echo "Changed files: ${{ env.DIFF_FILES }}"
