name: Git Diff Workflow
on: [push]

jobs:
  git-diff-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Git Diff
        run: |
          git diff --name-only HEAD^ HEAD
          echo "::set-output name=diff-files::$(git diff --name-only HEAD^ HEAD)"
